spring.application.name=bilim_scan
server.port=${SERVER_PORT:4257}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://dbadmin:pghrH0UcQKFbhB5sQagm3xNVPMsqV1qH@localhost:27017/bilim_scan?authSource=admin}
jwt.secret=${JWT_SECRET:oW06XK9Gb4ZhWLgGacqKAZyhPKV0Gatf}
jwt.expiration-ms=${JWT_EXPIRATION_MS:10800000}
bootstrap.admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:true}
bootstrap.admin.username=${BOOTSTRAP_ADMIN_USERNAME:admin}
bootstrap.admin.password=${BOOTSTRAP_ADMIN_PASSWORD:admin123}
# Rasm saqlanadigan papka nomi
file.upload-dir=uploads/profiles

# Fayl hajmi uchun cheklovlar (masalan, 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB